HyperAuth 연동, GNB 기능 추가
tmax-cloud/hypercloud-console4.2 pull request #19
Opened 2020-11-09 07:23 UTC by soyoungshim

# HyperAuth 연동, GNB 기능 추가
#### What:  HyperAuth 연동, GNB 계정 관련 컴포넌트, 언어 변경 컴포넌트 추가
  - HyperAuth 로그인
  - GNB
    - 세션 유효 시간,  유효 시간 연장 버튼, 세션 만료 팝업 컴포넌트 추가
    - 로그아웃 버튼 연동, account console 링크 연동
    - 언어 변경 기능 추가

#### Why: HyperAuth 연동, i18n 언어 변경 기능이 필요해서

#### How: 
- HyperAuth
  - keycloak-js, @react-keycloak/web 패키지 
    - ReactKeycloakProvider , withKeycloak 등 라이브러리 제공 기능 사용
  - 유효 시간 관련 기능 , 언어 변경 기능은 기존 4.1 컴포넌트 활용

2020-11-12 02:34 UTC, yjChoi2468 requested changes
추후에는 기능별로 나눠서 PR을 날리는면 리뷰에도 좋고, merge 단위 나누기에도 좋을거 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +  console.log('[onKeycloakEvent]', event, error);
개발 test용 log는 삭제하는 것이 깔끔할 것 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakTokens]', tokens);
해당 주석은 의미가 없는거 같고, 함수도 실행문이 없어서 의도를 파악하기가 어렵습니다. 필요한 함수라면 함수에 대한 설명을 넣어 두는 것을 어떨까요?

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +};
개인적인 취향으로는 switch 문에서 동작이 없는 case에 대해서는 fall through를 이용하여 합치면 가독성에 도움이 될거 같아요! 그러나 일반적으로 fall through를 지양하는거 같기는 해서 개인 취향면에서만 의견을 살포시 내밀어봅니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +              )}
줄 정리 commit을 분리하면 기능 추가 로직을 추적하기 더 좋을거 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +    // };
deprecated 코드는 삭제하는 것이 좋을 것 같습니다! 만약 언제 또 hyperauth가 사라질 지 몰라 놔두신 거라면, 히스토리를 위해 주석 처리한 이유를 명확하게 적어두는건 어떨까요?

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/hypercloud/keycloak.js
> +});
이거는 어떤 연유로 TODO로 남은건가요? console server 쪽에 이슈가 있는건가요?

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +          console.log('tokenTimeoutHandle', keycloak.tokenTimeoutHandle);
개발 test용 log는 제거하는 것이 좋을거 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +      // }
마찬가지로 주석을 삭제하거나 deprecated된 이유를 적어주면 좋을거 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +      label: 'Manage Account',
i18n은 아직 string이 나오지 않은건가요?

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +    this._renderI18n = this._renderI18n.bind(this);
renderI18n 함수가 LanguageDropdown 위젯을 그리는 것으로 보이는데 한 기능에 대해서 한 쪽으로 이름을 통일하면 해석에 도움이 될거 같습니다! (ex. _renderLanguageDropdown)

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/masthead-toolbar.jsx
> +      // window.location.reload();
이 코드는 주석처리된 이유가 무엇인가요? 그리고 주석처리되었는데 남아있는 특별한 이유가 있나요?

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/modals/modal.tsx
> +export const CustomModalSubmitFooter: React.SFC<CustomModalSubmitFooterProps> = ({
식별자명이 custom인 이유가 있나요? hypercloud에서 일반적으로 사용하는 형태가 아닌가요?
(hypercloud에서 공통으로 사용할 component라면 HyperCloud나 Common이라는 용어가 들어가는게 조금 더 적합할거 같아서요)

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> +          <div className="form-group" style={{ width: '400px' }}>
inline style은 특별한 이유가 없으면 지양하는 것이 오류를 줄이기에 좋을거 같습니다!

2020-11-12 02:34 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> +};
이 props들의 용도는 무엇인가요?

2020-11-12 02:48 UTC, soyoungshim commented on frontend/public/components/app.jsx
> +};
네넵! 의견 감사합니다 저는 switch 문은 제 취향 그대로 냅두겠습니다!ㅎㅎ

2020-11-12 04:43 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +              )}
네 알겠습니다!

2020-11-12 04:45 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +      // window.location.reload();
기존 코드에 있던 부분이라서 주석처리 한 것이였는데 삭제하는게 맞는 것 같아 삭제하겠습니다.

2020-11-12 04:48 UTC, soyoungshim commented on frontend/public/components/hypercloud/modals/modal.tsx
> +export const CustomModalSubmitFooter: React.SFC<CustomModalSubmitFooterProps> = ({
일반적으로 사용하는 형태는 보통 Action 버튼 과 Cancel 버튼이 기본적으로 들어가는데 이 dialog 는 취소 버튼 없이 action 버튼이 두개입니다. 컴포넌트 명은 제가 지은 건 아니고 4.1에 있는 기존 컴포넌트를 그대로 가져왔던 부분이라서 수정 시 4.1 컴포넌트 명도 같이 바꿔야할 것 같습니다.

2020-11-12 04:48 UTC, soyoungshim commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> +          <div className="form-group" style={{ width: '400px' }}>
이부분도 기존 컴포넌트를 그대로 가져와서 신경쓰지 못했던 부분인데 수정하겠습니다.

2020-11-12 04:49 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +    this._renderI18n = this._renderI18n.bind(this);
_renderMenu 함수랑 비슷한 역할을 해서 _renderLanguageMenu 로 수정하였습니다.

2020-11-12 04:50 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +    // };
혹시나 해서 남겨두었던건데 삭제하는게 맞는 것 같아 삭제했습니다.

2020-11-12 04:51 UTC, soyoungshim commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakTokens]', tokens);
사용하지 않는 함수여서 이부분 삭제했습니다.

2020-11-12 04:51 UTC, soyoungshim commented on frontend/public/components/app.jsx
> +  console.log('[onKeycloakEvent]', event, error);
콘솔 로그 제거하였습니다.

2020-11-12 06:03 UTC, soyoungshim commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> +};
안쓰는 props라서 삭제하였습니다.

2020-11-12 08:48 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakEvent]', event, error);
음...해당 주석은 필요해서 남겨두신걸까요..?

2020-11-12 08:48 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakTokens]', tokens);
LGTM

2020-11-12 08:48 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +  console.log('[onKeycloakEvent]', event, error);
LGTM

2020-11-12 08:48 UTC, yjChoi2468 commented on frontend/public/components/app.jsx
> +};
LGTM

2020-11-12 08:55 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> -  cancel: PropTypes.func.isRequired,
cancel prop은 _logout 함수에서 사용하는거 같은데 지워도 문제는 없는건가요?

2020-11-13 04:45 UTC, soyoungshim commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakEvent]', event, error);
개발할 때 주석 풀어서 사용하면 편할 것 같아서 남겨두었습니다

2020-11-13 05:43 UTC, soyoungshim commented on frontend/public/components/hypercloud/modals/notice-expiration-modal.jsx
> -  cancel: PropTypes.func.isRequired,
네 우리가 직접 넣는 props가 아니라 createModalLauncher에서 전달해주는 값이라서 propsType지정하는 부분은 지워도 상관없습니다.

2020-11-13 05:50 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +      // }
네넵 주석 삭제했습니다!

2020-11-13 05:50 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +      label: 'Manage Account',
나왔습니다! 이번 PR 합친 뒤 추가하려고 합니다.

2020-11-13 05:52 UTC, soyoungshim commented on frontend/public/hypercloud/keycloak.js
> +});
변수 처리는 이번 PR이후 추가하려고 TODO로 해놓았습니다.

2020-11-13 05:53 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +          console.log('tokenTimeoutHandle', keycloak.tokenTimeoutHandle);
삭제했습니다!

2020-11-13 06:01 UTC, mjsso approved these changes
i18n 변경 기능은 언어 파일이 2 depth일 때도 정상동작하는 것 테스트를 통해 확인하였습니다. 본 PR 머지 시 현재 예시로 구현된(예: "Home"/"홈" 표시부분) 부분의 키값들도 앞에 namespace를 추가해줘야 정상동작 하게 됩니다.

2020-11-13 06:47 UTC, soyoungshim commented
샘플에 적용된 i18n (홈, 삭제) 2depth json에 맞게 수정하였습니다.

2020-11-13 06:48 UTC, yjChoi2468 commented on frontend/public/hypercloud/keycloak.js
> +});
아하 넵

2020-11-13 06:49 UTC, yjChoi2468 approved these changes

2020-11-13 07:29 UTC, mjsso commented on frontend/public/components/hypercloud/modals/modal.tsx
> +export const CustomModalSubmitFooter: React.SFC<CustomModalSubmitFooterProps> = ({
Footer 하단의 두 버튼의 text와 동작을 모두 커스터마이징 할 수 있게끔 만들어놓은 것 같아서 저는 Common의 개념보다는 Custom의 개념이 더 알맞다고 느껴집니다. HyperCloud에서 ModalSubmitFooter(Cancel, Action버튼으로 구성)를 Common한 Footer로 사용중이라고 한다면 두 버튼 모두 바꿀 수 있는건 CustomModalSubmitFooter로 두는 것도 괜찮다고는 생각이듭니다..! 아니면 props로 커스터마이징 여부를 정해서 cancel버튼을 커스터마이징 할 수있게해주는 HyperCloud용 CommonModalSubmitFooter를 만드는 것도 괜찮을 것 같은데 공수가 더 들겠네요.. 어떻게 생각하시나요?

2020-11-13 07:34 UTC, mjsso commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakEvent]', event, error);
주석으로 남겨놓으면 매번 코드를 다시 작성하지 않아도 돼서 편하긴 하지만 로그 내용이 간단해서 eventLogger에서 로그를 찍어야 할 경우에만 코드를 추가해서 로그를 찍도록 해도 괜찮을 것 같습니다..!ㅎㅎ

2020-11-13 07:36 UTC, soyoungshim commented on frontend/public/components/hypercloud/modals/modal.tsx
> +export const CustomModalSubmitFooter: React.SFC<CustomModalSubmitFooterProps> = ({
의견 감사합니다. 제 생각에는 공수도 그렇고 action 버튼 두개에 cancel 버튼이 들어갈 경우가 없을 것 같아 현재 상태 그대로 가는게 좋을 것 같습니다.

2020-11-13 07:40 UTC, mjsso commented on frontend/public/components/hypercloud/modals/modal.tsx
> +export const CustomModalSubmitFooter: React.SFC<CustomModalSubmitFooterProps> = ({
아 제 의견은 cancel버튼 자리에 action버튼을 둬서 두 개의 action으로 구성된 footer를 만들게끔 하는 것이였습니다..ㅎㅎ 하지만 공수가 들 것 같아 저도 현재 상태로 가는 것이 더 나을 것 같다고 생각합니다.

2020-11-13 07:41 UTC, soyoungshim commented on frontend/public/components/app.jsx
> +  // console.log('[onKeycloakEvent]', event, error);
네 코멘트달아주신대로 주석 삭제했습니다!

2020-11-16 01:48 UTC, merged