Feature/add dropdown component
tmax-cloud/hypercloud-console4.2 pull request #22
Opened 2020-11-11 10:54 UTC by hyejjjjin

**What**
- react-hook-form을 적용한 Dropdown, ContainerDropdown 컴포넌트 구현
  - required 속성을 통한 validation
  - defaultValues를 통한 초기값 지정
- create-sample 페이지에 예시 추가

**How**
- Title 부분(선택된 상태)에 아이콘이 들어가는 경우가 있으므로  useEffect, setValue 이용하는 방법 이용
- defaultValues로 초기화할 수 있도록 watch 이용

2020-11-12 05:58 UTC, yeonggyulim approved these changes
확인했습니다

2020-11-20 07:16 UTC, yjChoi2468 requested changes

2020-11-20 07:16 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/utils/dropdown.jsx
>  };
파일 맨 끝에 개행 문자를 추가하면 좋을 것 같습니다. (프리티어에서 자동으로 해주는 걸로 아는데 혹시 적용이 안되었던 걸까요?)
https://minz.dev/19

2020-11-20 07:16 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +    }
arrow key로 이동할 때, 어느 item이 선택되어 있는지 표시하지는 않아도 되나요? (advanced 기능 같아서 코멘트만 살포시 남겨봅니다)

2020-11-20 07:16 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +};
ContainerDropdown은 어떤 기능을 구현한 컴포넌트인가요?
ResourceDropdown이라고 들었는데 맞나요?

(ResourceDropdown이 맞으면
1. 이름을 ContainerDropdown으로 변경한 이유가 있으실까요?
2. Resource를 get 해오는 부분이 어디인지 궁금합니다.)

2020-11-20 07:16 UTC, yjChoi2468 commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +      >
full, 1/2, 1/3 등 width를 유연하게 적용할 수 있으면 가져다 쓰기 좋을거 같습니다!

2020-11-26 09:19 UTC, yjChoi2468 approved these changes

2020-12-01 07:52 UTC, hyejjjjin commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +};
ResourceDropdown과는 다른 것입니다. 컨테이너를 선택할 수 있도록 만들어진 Dropdown입니다! ResourceDropdown은 추후 추가하겠습니다.

2020-12-01 08:10 UTC, hyejjjjin commented on frontend/public/components/hypercloud/utils/dropdown.jsx
>  };
참고하겠습니다!

2020-12-01 11:12 UTC, mjsso approved these changes
확인했습니다.

2020-12-04 08:29 UTC, hyejjjjin commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +    }
의견 반영하여 수정했습니다.

2020-12-04 08:32 UTC, hyejjjjin commented on frontend/public/components/hypercloud/utils/dropdown.jsx
> +      >
의견 주신 부분을 정확히 이해하지 못했는데... 물어볼 수가 없네요...ㅠdropDownClassName, buttonClassName, menuClassName 세가지 className을 받아서 적용해주고 있는 부분이 있어서 우선 예시에 추가해두었습니다..! 추후

2020-12-04 08:34 UTC, merged