GNB 컨텐츠 i18n 적용
tmax-cloud/hypercloud-console4.2 pull request #23
Opened 2020-11-16 05:01 UTC by soyoungshim

#### What: GNB i18n 적용

#### Why: i18n 적용이 필요해서

#### How: react-i18next 라이브러리 사용
- masthead-toolbar
  - MastheadToolbarContents_ 컴포넌트가 클래스형 컴포넌트이며, 중간중간 함수 내 로직에 String 을 넣어주어야 하는 부분이 있어 withTranslation 을 사용했습니다. 좋은 아이디어 있으면 공유 부탁드립니다. 
- 세션 팝업
  - 팀 내 i18n 적용 가이드대로 Translation 태그 사용하였습니다.

2020-11-17 07:01 UTC, eunkyeng requested changes

2020-11-17 07:01 UTC, eunkyeng commented on frontend/public/components/masthead-toolbar.jsx
> +      label: t('COMMON:MSG_GNB_ACCOUNT_1'),
이부분 userAction 배열안에 객체로 label의 값이 넘어가고 userAction이 actions배열로 넘어가서 _renderApplicationItems함수의 파라미터로 넘어가는데 (296L) 이부분에서 <Translation>으로 처리가 불가능한건가요?

2020-11-17 08:27 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +      label: t('COMMON:MSG_GNB_ACCOUNT_1'),
_renderApplicationItems 함수 내부에서의 처리는 힘들 것 같고 _renderApplicationItems 함수를 호출하는 시점에 넣어주어야 할 것 같습니다.

2020-11-17 08:57 UTC, soyoungshim commented on frontend/public/components/masthead-toolbar.jsx
> +      label: t('COMMON:MSG_GNB_ACCOUNT_1'),
현재 `MastheadToolbarContents_ ` 컴포넌트에서  i18n 을 사용하는 부분이 총 5곳에 분산 되어 있는데 사용하는 부분마다 <Translation>을 사용하는 것 보다는 withTranslation 을 사용해서 props로 꺼내 쓰는 방법이 좀 더 중복 코드를 줄이고 좋은 방법이라고 생각됩니다.  특히 말씀해주신 부분에서 userAction 배열 내 항목을 구성할 때 t가 필요한데, 이 부분을 Translation 태그 방식으로 변경할 경우 return 문의 `_renderApplicationItems `에서 각각 <Translation>을 감싸주어야 합니다. 이 과정에서 action 배열을 각각 두 개를 따로 만들어야 하기 때문에 이 경우에는 withTranslation을 사용해 props에서 꺼내서 사용하는 것이 맞는 것 같습니다!

2020-11-19 05:26 UTC, mjsso approved these changes
확인했습니다.

2020-11-19 05:38 UTC, merged